### ISSUE TITLE
Issues with Link->getCategoryLink

### ISSUE THREAD

**Issue by svensson-david** [ZiZuu-store/PrestaShop_module-zzCleanURLs#6]
I was having some issues with the overridden Link class when calling getCategoryLink in multiple places on a page. In my case a footer and a header menu.

The problem was that the category links wound up missing the parent category slug the second time the getCategoryLink-function was called.

It seems the problem was that the category_disable_rewrite-array built itself larger and larger on each request not resetting when necessary.

I changed the function in Link.php back so it looked like the original Lebioda version and it works ok

row 60-63 in Link.php
```
if (!in_array($p_cat['id_category'], array(1, 2, $category->id))) {
  $p_cats[] = $p_cat['link_rewrite'];
}
```
Let me know if you've had the same issues and if you want me to fork and fix.

**Comment by ZiZuu-store** [comment]
Hi @svensson-david,
  yes please fork and test if it works in any case for your store .. so I can merge

Thanks

**Comment by ZiZuu-store** [comment]
please try the current dev

**Comment by svensson-david** [comment]
Will do!
I'm out traveling until next weekend but will check as soon as possible after that.

**Comment by ZiZuu-store** [comment]
@svensson-david any news?

**Comment by ZiZuu-store** [comment]
I'm confident the fix is ok .. if any issue please report here (will leave this issue unlocked)
