### ISSUE TITLE
categories: {rewrite}/

### ISSUE THREAD

**Issue by ebinx** [ZiZuu-store/PrestaShop_module-zzCleanURLs#7]
I'd like to be able to "mark" all category friendly urls with a preceding "c/" (which stands for category) to achieve category URLs such as:
example.com/c/shirts
example.com/c/trousers

I tried to put
```
c/{rewrite}/
```
into a friendly URL field for category path, but it did not work.

How can I get category URL's in a format  "c/{rewrite}/"?

**Comment by ZiZuu-store** [comment]
Hello @ebinx 

  **c/{rewrite:/}**  should work

**Comment by ZiZuu-store** [comment]
@ebinx did it work?

**Comment by ebinx** [comment]
It didn't work (PS 1.6.1.0)

**Comment by ebinx** [comment]
OK fixed it.
In override/classes/Dispatcher.php there is a function "isCategoryLink". All I did was to change an array item number from 0 to 1.
from:
`WHERE `link_rewrite` = \''.pSQL($categories[0]).'\' AND `id_lang` = '.(int)Context::getContext()->language->id;`
to:
`WHERE `link_rewrite` = \''.pSQL($categories[1]).'\' AND `id_lang` = '.(int)Context::getContext()->language->id;`

**Comment by ZiZuu-store** [comment]
uhm .. do you have an idea of the reason?

I think this trick should not be the solution (even if it works) .. we shall investigate the root reason .. I guess that if you remove the "/c" prefix and leave the hack there it will not work again

I'll change this issue into a bug to be fixed

**Comment by ZiZuu-store** [comment]
@ebinx please try the current dev Dispatcher.php

**Comment by ebinx** [comment]
I'll try new dev when I get back home. What I did was a quick solution to
my needs and not a fix. I realised dispatcher.php after exploding url was
looking for the 1st [0]item in array, and when it found my "c" it could not
find corresponding category in db...

wt., 25 sie 2015, 11:52 ZiZuu.com użytkownik <notifications@github.com>
napisał:

**Comment by ZiZuu-store** [comment]
@ebinx ok thank you.

Please note I was not pointing out your fix was not good .. if I did so my apologies .. my bad (english :P)

The current dev should fix, but I'm planning to do a better rewrite of the entire logic asap

Thank you for your help, looking forward for your feedback as soon as you have tested .. thanks again

**Comment by ebinx** [comment]
Current dev works like a charm :+1:
grazzie mile!

**Comment by ZiZuu-store** [comment]
:+1: 

Prego :)
